# Define Path

In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
BASE_PATH = 'gdrive/My Drive/Binus S2 MTI/3. Machine Learning/Assignment & AoL/'
# BASE_PATH = './'
DATA_PATH = BASE_PATH + 'data/'
MODEL_PATH = BASE_PATH + 'models/'

# Import Libaries

In [ ]:
!pip install category_encoders
!pip install catboost

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [ ]:
import pandas as pd
from category_encoders.one_hot import OneHotEncoder
import joblib

In [ ]:
columns = [
    'age',
    'job',
    'marital',
    'education',
    'default',
    'balance',
    'housing',
    'loan',
    'contact',
    'month',
    'duration',
    'campaign',
    'previous',
]

# values = [
#     [35, 'admin.', 'married', 'secondary', 'no', 214,
#      'yes', 'yes', 'unknown', 'jun', 247, 1, 0]
# ]

values = [
    [50, 'management', 'married', 'tertiary', 'yes',
     5000, 'yes', 'yes', 'cellular', 'feb',
     2000, 2, 2]
]

X_test = pd.DataFrame(values, columns=columns)
X_test

,age,job,marital,education,default,balance,housing,loan,contact,month,duration,campaign,previous
0,50,management,married,tertiary,yes,5000,yes,yes,cellular,feb,2000,2,2

In [ ]:
# import one hot encoder
ohe = joblib.load(MODEL_PATH + 'ohe.pkl')
ohe

OneHotEncoder(cols=['job', 'marital', 'education', 'default', 'housing', 'loan',
                    'contact', 'month'])

In [ ]:
X_test_enc = ohe.transform(X_test)
X_test_enc

,age,job_1,job_2,job_3,job_4,job_5,job_6,job_7,job_8,job_9,...,month_6,month_7,month_8,month_9,month_10,month_11,month_12,duration,campaign,previous
0,50,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2000,2,2

In [ ]:
# import cbc_optuna
cbc_optuna = joblib.load(MODEL_PATH + 'cbc_optuna.pkl')
cbc_optuna

CatBoostClassifier(bagging_temperature=1.8338907059247582, border_count=153, depth=10, iterations=861, l2_leaf_reg=7.517679331255321, learning_rate=0.09895366896644066, od_type='IncToDec', od_wait=50, random_state=1, random_strength=8.291845426654422, verbose=False)

In [ ]:
best_thres_accuracy = 0.4963388427754832
best_thres_accuracy

0.4963388427754832

In [ ]:
model_proba = cbc_optuna.predict_proba(X_test_enc)

# Ambil probabilitas kelas 1
prob = model_proba[0][1]

# Prediksi berdasarkan threshold
model_pred = 'The client is predicted not to subscribe a term deposit.' if prob < best_thres_accuracy else 'The client is predicted to subscribe a term deposit.'

percentage = model_proba[0][1] * 100

print(f"Probability Percentage = {percentage:.2f}%")
print(model_pred)

Probability Percentage = 71.62%
The client is predicted to subscribe a term deposit.